"""initial tables

Revision ID: 0e55b3cbfd09
Revises: 
Create Date: 2026-09-04 13:07:00.144760

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e55b3cbfd09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_github_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=True)
    op.create_index(op.f('ix_user_github_username'), 'user', ['github_username'], unique=True)
    op.create_table('githubstatscache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('top_languages_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pinned_repos_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_githubstatscache_user_id'), 'githubstatscache', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_githubstatscache_user_id'), table_name='githubstatscache')
    op.drop_table('githubstatscache')
    op.drop_index(op.f('ix_user_github_username'), table_name='user')
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
