"""add refresh token column

Revision ID: 97fd6832318d
Revises: 0e55b3cbfd09
Create Date: 2026-09-04 17:27:04.407499

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fd6832318d'
down_revision: Union[str, Sequence[str], None] = '0e55b3cbfd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('encrypted_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'encrypted_refresh_token')
    # ### end Alembic commands ###
